[package]
name = "example_3_protobuf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"

[build-dependencies]
# it needs to be the same version as prost
prost-build = "0.12"